### ISSUE TITLE
blows up when num-iters > 1

### ISSUE THREAD

**Issue by mchampine** [aria42/type-level-tagger#1]
$ cljr run tagger.clj infile outfile 2 5 1 0.1
Learning on  2  iterations.
Num Word Types: 35 Num Tokens: 75
Finished Iteration 1 (Random) Wrote current assignment to outfile
java.lang.AssertionError: Assert failed: (neg? %) (tagger.clj:0)
...etc...
Caused by: java.lang.AssertionError: Assert failed: (neg? %)
        at type_level_tagger$log_prob.invoke(tagger.clj:40)
        at type_level_tagger$score_assign$t1__1462.invoke(tagger.clj:206)

**Comment by aria42** [comment]
Oh that's because you're running with so little data a probability becomes one. Probably shouldn't run the code with less than about 100k tokens. I'll remove the assert though.

**Comment by aria42** [comment]
I changed the code to remove the assert, but you probably are going to have other issues on that little data.
